### ISSUE TITLE
combo_results_all1.csv is missing

### ISSUE THREAD

**Issue by Banhalmi** [iyempissy/anonymization-reconstruction-attack#1]
Dear Authors,
I would like to check the los_prediction.py code, and was done the preprocessing of the referenced project. I don't have combo_results_all1.csv in the views folder.
The los_prediction.py is looking for it.
How that file can be made?

**Comment by iyempissy** [comment]
The MIMIC data is private and has to be obtained from https://mimic.mit.edu/docs/gettingstarted/

For getting the corresponding files for the k_anonymity, you can do that via the ARX tool (https://arx.deidentifier.org/) after preprocessing and getting the data.
