### ISSUE TITLE
only_demographics: no key 'ethnicity_grouped'

### ISSUE THREAD

**Issue by Banhalmi** [iyempissy/anonymization-reconstruction-attack#2]
# used ethnicity_grouped instead of ethnicity so as to remove some other tribes that are not entirely necessary
        cohort = cohort[['subject_id', 'hadm_id', 'age', 'ethnicity_grouped', "los_hospital", "los_icu", "gender", "first_hosp_stay", "first_icu_stay"]]

There is not this key: 'ethnicity_grouped'

**Comment by iyempissy** [comment]
Yes, this can be created by grouping ethnicity into higher order
