### ISSUE TITLE
only_demographics.py: there are no processed data variants

### ISSUE THREAD

**Issue by Banhalmi** [iyempissy/anonymization-reconstruction-attack#3]
The preprocessing code generates just one processed_data.csv.
However there should be 10 different ones, the first one which is not found is: views/processed_datak10.csv

**Comment by iyempissy** [comment]
For getting the corresponding files for the k_anonymity, you can do that via the ARX tool (https://arx.deidentifier.org/) after preprocessing and getting the data.
